<?php
/**
 * AbstractDefaultApi
 *
 * PHP version 7
 *
 * @package OpenAPIServer\DefaultApi
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * Assessment API
 *
 * Assessment API
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */
namespace OpenAPIServer\Api;

use Psr\Container\ContainerInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\ResponseInterface;
use Exception;

/**
 * AbstractDefaultApi Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
abstract class AbstractDefaultApi
{

    /**
     * @var ContainerInterface Slim app container instance
     */
    protected $container;

    /**
     * Route Controller constructor receives container
     *
     * @param ContainerInterface $container Slim app container instance
     */
    public function __construct(ContainerInterface $container)
    {
        $this->container = $container;
    }


    /**
     * GET questionsGet
     * Summary: Returns the list of translated questions and associated choices
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param array|null             $args     Path arguments
     *
     * @return ResponseInterface
     * @throws Exception to force implementation class to override this method
     */
    public function questionsGet(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $message = "How about implementing questionsGet as a GET method in OpenAPIServer\Api\DefaultApi class?";
        return $response->write($message)->withStatus(501);
    }

    /**
     * POST questionsPost
     * Summary: Creates a new question and associated choices (the number of associated choices must be exactly equal to 3)
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param array|null             $args     Path arguments
     *
     * @return ResponseInterface
     * @throws Exception to force implementation class to override this method
     */
    public function questionsPost(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $message = "How about implementing questionsPost as a POST method in OpenAPIServer\Api\DefaultApi class?";
        return $response->write($message)->withStatus(501);
    }
}
