<?php
/**
 * Question
 *
 * PHP version 7
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use DateTime;

/**
 * Question
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class Question
{
    
    /** @var string $text */
    public $text;
    
    /** @var DateTime $createdAt Creation date of the question*/
    public $createdAt;
    
    /** @var Choice[] $choices Choices associated to the question*/
    public $choices;

    public function __construct(string $text, DateTime $createdAt, array $choices)
    {
        $this->text = $text;
        $this->createdAt = $createdAt;
        $this->choices = $choices;
    }
}
