<?php
/**
 * Question
 *
 * PHP version 7
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

/**
 * Question
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class Question
{
    
    /** @var string $text */
    private $text;
    
    /** @var \DateTime $createdAt Creation date of the question*/
    private $createdAt;
    
    /** @var \OpenAPIServer\Model\Choice[] $choices Choices associated to the question*/
    private $choices;
}
